### ISSUE TITLE
Lab Feedback

### ISSUE THREAD

**Issue by JGMSoftware** [richarvey/techshift-modernise#45]
Hi folks, I attended the workshop in London last week and I'm running through the labs again. I've got some feedback/suggested changes for Lab 2 - as I go through the labs, if I find anything would you rather I reported them as issues or opened PRs for them?

In Lab 2, Step 4, the CloudFormation deploys a second public subnet with `MapPublicIpOnLaunch: false` - is this intentional? I don't think this could lead to unintended consequences within the lab material, but if someone is trying to extend it for themselves then it may lead to confusion if they deploy their own instances.

Similarly, in Step 6, the CloudFormation deploys two private subnets with `MapPublicIpOnLaunch: true` - I don't think this makes sense in the context of a private subnet?

**Comment by richarvey** [comment]
Good spot, we'll get this fixed asap.

**Comment by richarvey** [comment]
this fix applies to lab2+ for MapPublicIpOnLaunch, will push change asap.
